version: "3"

services:
  proxy:
    image: nginx
    container_name: prd-desafio-fullstack-nginx
    ports:
      - "80:80"
    volumes:
      - "./docker/production/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./frontend/dist:/var/www/html"
    networks:
      - desafio-fullstack-network

  backend:
    build:
      context: .
      dockerfile: docker/production/php/Dockerfile
    image: dev-desafio-fullstack-backend
    container_name: prd-desafio-fullstack-backend
    stdin_open: true
    tty: true
    working_dir: /var/www/html
    volumes:
      - ./backend/:/var/www/html
    networks:
      - desafio-fullstack-network

  frontend:
    build:
      context: .
      dockerfile: docker/production/node/Dockerfile
    working_dir: /app
    stdin_open: true
    tty: true
    ports:
      - "5173:5173"
    image: dev-desafio-fullstack-frontend
    container_name: prd-desafio-fullstack-frontend
    volumes:
      - ./frontend/:/app
    networks:
      - desafio-fullstack-network

  database:
    image: mysql:8.0.36
    container_name: prd-desafio-fullstack-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: desafio
    volumes:
      - ./.database:/var/lib/mysql
    networks:
      - desafio-fullstack-network

networks:
  desafio-fullstack-network:
    driver: bridge
