<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Product>
 */
class ProductFactory extends Factory
{
    private $products = [
        "Smartphone Samsung Galaxy S21",
        "Laptop Dell XPS 13",
        "Relógio Rolex Submariner",
        "Mochila Herschel Supply Co.",
        "Perfume Chanel Coco Mademoiselle",
        "Tênis Nike Air Max 270",
        "Guitarra Fender Stratocaster",
        "Conjunto de panelas Tramontina",
        "Televisão Samsung QLED 4K",
        "Cafeteira Nespresso Vertuo",
        "Livro '1984 de George Orwell",
        "Bolsa Louis Vuitton Neverfull",
        "Tênis Adidas Ultraboost",
        "Mesa de jantar de madeira maciça",
        "Câmera Canon EOS R5",
        "Colchão de molas ensacadas",
        "PlayStation 5",
        "Drone DJI Mavic Air 2",
        "Mixer de mão KitchenAid",
        "Conjunto de malas de viagem Samsonite",
        "Anel de diamante solitário",
        "Mouse Logitech MX Master",
        "Smartwatch Apple Watch Series 7",
        "Fone de ouvido Sony WH-1000XM4",
        "Lâmpada inteligente Philips Hue",
        "Camisa social Ralph Lauren",
        "Conjunto de copos de cristal",
        "Máquina de lavar roupa LG",
        "Cafeteira Italiana Bialetti",
        "Saco de dormir Marmot",
        "Prancha de surf Channel Islands",
        "Colar de pérolas Mikimoto",
        "Conjunto de talheres de prata",
        "Carteira de couro Montblanc",
        "Bicicleta de montanha Trek",
        "Bolsa de golfe Titleist",
        "Perfume Dior Sauvage",
        "Poltrona Eames Lounge",
        "Conjunto de malas de maquiagem",
        "Relógio Casio G-Shock",
        "Tênis Converse Chuck Taylor All Star",
        "Teclado mecânico Corsair",
        "Sofá de couro Chesterfield",
        "Violão Taylor 814ce",
        "Cadeira de escritório Herman Miller Aeron",
        "Mala de ferramentas Stanley",
        "Carro elétrico Tesla Model S",
        "Bola de basquete Spalding NBA",
        "Bolsa tote de couro Coach",
        "Conjunto de facas de cozinha Wüsthof",
        "Tênis de corrida Brooks Ghost",
        "Escova de dentes elétrica Oral-B",
        "Conjunto de toalhas de banho Ralph Lauren",
        "Capacete de motocicleta Shoei",
        "Jogo de panelas de ferro fundido Lodge",
        "Banheira de hidromassagem Jacuzzi",
        "Trompete Yamaha YTR-2330",
        "Máquina de cortar cabelo Wahl",
        "Churrasqueira a gás Weber",
        "Óculos de sol Ray-Ban Aviator",
        "Bola de futebol Adidas Telstar",
        "Conjunto de lençóis de algodão egípcio",
        "Forno de embutir Electrolux",
        "Banqueta de bar Eames",
        "Relógio de pulso Omega Speedmaster",
        "Adega climatizada Brastemp",
        "Patins rollerblade",
        "Conjunto de pratos de porcelana",
        "Sofá-cama Ikea",
        "Caixa de som JBL Charge",
        "Carteira de motorista de couro",
        "Bicicleta dobrável Brompton",
        "Cadeira gamer DXRacer",
        "Cadeado TSA",
        "Notebook Apple MacBook Pro",
        "Roteador Wi-Fi TP-Link",
        "Conjunto de pincéis de maquiagem",
        "Tela de projeção motorizada",
        "Lancheira térmica Yeti",
        "Conjunto de chave de fenda",
        "Patinete elétrico Xiaomi Mi",
        "Travesseiro de plumas de ganso",
        "Escova de cabelo Tangle Teezer",
        "Máquina de costura Singer",
        "Cama box com colchão de molas",
        "Caixa de ferramentas Husky",
        "Chaleira elétrica Hamilton Beach",
        "Mesa de centro de vidro",
        "Cadeira de balanço de madeira",
        "Tela de TV OLED LG",
        "Caixa de som portátil Bose SoundLink",
        "Kit de limpeza para sapatos",
        "Kit de churrasco completo",
        "Colete salva-vidas Mustang Survival",
        "Roteador de mesa Asus",
        "Berço de bebê conversível",
        "Conjunto de malas de viagem Rimowa",
        "Gravador de voz Zoom H6",
        "Babá eletrônica Motorola",
        "Estojo de maquiagem profissional",
        "Varal retrátil de parede",
        "Relógio de parede cuco",
        "Violino Stradivarius",
        "Serra elétrica Makita",
        "Amplificador de guitarra Fender Twin Reverb",
        "Kit de ferramentas para churrasco",
        "Estação de trabalho ajustável em altura",
        "Mini geladeira portátil",
        "Kit de camping completo",
        "Cortador de grama elétrico",
        "Soprador de folhas a bateria",
        "Mini projetor portátil",
        "Roteador sem fio de alta velocidade",
        "Bicicleta elétrica dobrável",
        "Conjunto de cabos de energia",
        "Aspirador de pó sem fio Dyson",
        "Sistema de som estéreo para casa",
        "Detector de fumaça inteligente",
        "Conjunto de ferramentas para jardinagem",
        "Luvas de jardinagem resistentes",
        "Kit de reparo de pneus de bicicleta",
        "Barraca para camping familiar",
        "Conjunto de chaves de fenda de precisão",
        "Balança de cozinha digital",
        "Fritadeira elétrica de ar",
        "Cadeira de acampamento dobrável",
        "Kit de acessórios para câmera GoPro",
        "Skate elétrico de longo alcance",
        "Estojo de ferramentas para bicicleta",
        "Bolsa de transporte para gato",
        "Lavadora de alta pressão Karcher",
        "Mochila de hidratação para ciclismo",
        "Capacete de bicicleta MIPS",
        "Luminária de mesa de LED",
        "Fogão portátil para acampamento",
        "Afiador de facas profissional",
        "Saco de pancadas",
    ];

    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            'name' => fake()->randomElement($this->products),
            'description' => fake()->text(),
            'price' => fake()->randomElement(range(0.99, 100)),
            'due_in' => fake()->date(),
            'image' => fake()->imageUrl(),
        ];
    }
}
